onEvent('jei.hide.items', event => {
	
	event.hide([
		/appliedenergistics2:facade/,
		'tconstruct:copper_ingot',
		'create:copper_ingot',
		'mekanism:ingot_copper',
		'janoeo:copper_ingot',
		// 'iceandfire:copper_ingot',
		'immersiveengineering:ingot_copper',
		'mekanism:ingot_tin',
    	'janoeo:tin_ingot',
		'janoeo:silver_ingot',
		'iceandfire:silver_ingot',
		'immersiveengineering:ingot_silver',
		'mekanism:ingot_lead',
		'janoeo:lead_ingot',
		'immersiveengineering:ingot_lead',
		'mekanism:ingot_bronze',
		'janoeo:zinc_ingot',
		'immersiveengineering:ingot_aluminum',
		'immersiveengineering:ingot_nickel',
		'janoeo:uranium_ingot',
		'mekanism:ingot_uranium',
		'bigreactors:yellorium_ingot',
		'immersiveengineering:ingot_constantan',
		'immersiveengineering:ingot_electrum',
		'mekanism:ingot_steel',
		'janoeo:osmium_ingot',
		'janoeo:copper_dust',
		'mekanism:dust_copper',
		'immersiveengineering:dust_copper',
		'janoeo:tin_dust',
    	'mekanism:dust_tin',
		'janoeo:silver_dust',
    	'immersiveengineering:dust_silver',
		'janoeo:lead_dust',
		'mekanism:dust_lead',
		'immersiveengineering:dust_lead',
		'mekanism:dust_bronze',
		'immersiveengineering:dust_aluminum',
		'immersiveengineering:dust_nickel',
    	'janoeo:nickel_dust',
		'janoeo:iron_dust',
		'mekanism:dust_iron',
		'appliedenergistics2:iron_dust',
		'immersiveengineering:dust_iron',
		'janoeo:gold_dust',
		'mekanism:dust_gold',
		'appliedenergistics2:gold_dust',
		'immersiveengineering:dust_gold',
		'bloodmagic:goldsand',
		'janoeo:uranium_dust',
		'mekanism:dust_uranium',
		'bigreactors:yellorium_dust',
		'immersiveengineering:dust_constantan',
		'immersiveengineering:dust_electrum',
		'immersiveengineering:dust_steel',
		'tconstruct:copper_nugget',
		'create:copper_nugget',
		'mekanism:nugget_copper',
		// 'iceandfire:copper_nugget',
		'immersiveengineering:nugget_copper',
		'mekanism:nugget_tin',
		'iceandfire:silver_nugget',
    	'immersiveengineering:nugget_silver',
		'mekanism:nugget_lead',
    	'immersiveengineering:nugget_lead',
		'mekanism:nugget_bronze',
		'immersiveengineering:nugget_nickel',
		'createdeco:netherite_nugget',
		'mekanism:nugget_uranium',
		'immersiveengineering:nugget_constantan',
		'immersiveengineering:nugget_electrum',
		'mekanism:nugget_steel',
		'tconstruct:copper_ore',
		'create:copper_ore',
		'mekanism:copper_ore',
		'janoeo:copper_ore',
		'iceandfire:copper_ore',
		'immersiveengineering:ore_copper',
		'mekanism:tin_ore',
    	'janoeo:tin_ore',
		'janoeo:silver_ore',
		'iceandfire:silver_ore',
		'immersiveengineering:ore_silver',
		'mekanism:lead_ore',
		'janoeo:lead_ore',
		'immersiveengineering:ore_lead',
		'janoeo:zinc_ore',
		'immersiveengineering:ore_aluminum',
		'immersiveengineering:ore_nickel',
		'janoeo:uranium_ore',
		'immersiveengineering:ore_uranium',
		'bigreactors:yellorite_ore',
		'janoeo:osmium_ore',
		'create:copper_sheet', 
    	'immersiveengineering:plate_copper',
		'immersiveengineering:plate_lead',
		'immersiveengineering:plate_silver',
		'createdeco:zinc_sheet',
		'immersiveengineering:plate_nickel',
		'immersiveengineering:plate_iron',
    	'create:iron_sheet',
		'immersiveengineering:plate_gold',
    	'create:golden_sheet',
		'immersiveengineering:plate_constantan',
		'immersiveengineering:plate_electrum',
		'titanium:diamond_gear',
		'titanium:gold_gear',
		'titanium:iron_gear',
		'createaddition:copper_wire'
	])
	
})

onEvent('jei.add.items', event => {
	
	event.add([
		Item.of('appliedenergistics2:facade', '{item:"minecraft:stone"}')
	])
	
})

onEvent('jei.information', event => {

	// event.add(item, [line1,line2,...])

})