#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "thermalexpansion", "tconstruct", "tmechworks", "create", "immersiveengineering", "mekanism", "thermalfoundation"]

